# Generated by Django 4.1.3 on 2022-12-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_alter_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tovars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtov', models.CharField(max_length=340, verbose_name='ID Товара')),
                ('name', models.TextField(verbose_name='Имя товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
