# Generated by Django 4.1.3 on 2022-12-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_tovars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovars',
            name='idtov',
        ),
        migrations.AddField(
            model_name='tovars',
            name='iddoc',
            field=models.CharField(default='Test', max_length=340, verbose_name='ID Чека'),
        ),
        migrations.AddField(
            model_name='tovars',
            name='kolvo',
            field=models.FloatField(default=1.0, verbose_name='Кол-во товара'),
        ),
        migrations.AddField(
            model_name='tovars',
            name='summa',
            field=models.FloatField(default=1.0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='name',
            field=models.CharField(max_length=340, verbose_name='Имя товара'),
        ),
    ]
