# Generated by Django 4.1.3 on 2022-12-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_alter_tovars_options_remove_tovars_iddoc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtov', models.CharField(default='default', max_length=30, verbose_name='ID товара')),
                ('name', models.CharField(default='default', max_length=400, verbose_name='Название товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Tovars',
        ),
        migrations.AlterField(
            model_name='checks',
            name='tovars',
            field=models.ManyToManyField(to='testApp.tovar', verbose_name='Товары в чеке'),
        ),
    ]
