# Generated by Django 4.1.3 on 2022-12-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_tovar_delete_tovars_alter_checks_tovars'),
    ]

    operations = [
        migrations.AddField(
            model_name='checks',
            name='count',
            field=models.FloatField(default=1.0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='checks',
            name='summa',
            field=models.FloatField(default=1.0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='tovars',
            field=models.ManyToManyField(related_name='tovar', to='testApp.tovar', verbose_name='Товары в чеке'),
        ),
    ]
