# Generated by Django 4.1.3 on 2022-12-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_checks_count_checks_summa_alter_checks_tovars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='idtov',
            field=models.CharField(default='default', max_length=30, null=True, verbose_name='ID товара'),
        ),
    ]
